### ISSUE TITLE
Bridge polygon to BSC issue

### ISSUE THREAD

**Issue by Gutinho9** [O3Labs/o3swap-audit#2]
I used the bridge to send money from polygon to bsc, 24 hours have passed and nothing, the money was deducted from my metamask at polygon and did not arrive at bsc

**Comment by rickcain** [comment]
Hi, there is a problem on polygon chain, you can check it [here](https://forum.polygon.technology/t/temporary-bor-hot-fix-v0-2-14-tmp-span-hotfix/2354), all cross chain transactions from polygon are paused for security reason. Once polygon chain is back to normal again, all pending transactions will continue cross chain.

**Comment by Frankdev012** [comment]
Talk to a Polygon Dev on the [**Live support page**](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by rickcain** [comment]
Cross-chain txs from/to Polygon is fully restored. Your transaction should be completed. If you have further questions, please open a new issue with txid attached.
